### PR TITLE
#6 password field

### PR DESCRIPTION
**Pull request by Shubham2301**

### CODE REVIEW

**Review by rathorevaibhav — APPROVED** [review]
Looks good to me! 👍

**Comment by rathorevaibhav** [comment]
Test feedback:
1. Able to set the password for a new guest.
2. I can RSVP using my email and an incorrect password. Are we tracking this in this PR or a different one?

**Comment by Shubham2301** [comment]
we are tracking pwd confirmation on 7th PR
but i will see that issue here also

**Comment by rathorevaibhav** [comment]
Then let's not fix it here. We'll take it forward on PR #13. This is good to merge.

**Comment by Shubham2301** [comment]
ok

**Pull request merged**
